Create database ola;
use ola;
select * from ola

--1. Retrieve all successful bookings:
select * from ola where Booking_Status= 'Success' 

--2. Find the average ride distance for each vehicle type:
select Vehicle_Type, avg(Ride_Distance) as avg_rides from ola group by Vehicle_Type

--3. Get the total number of cancelled rides by customers:select count(Booking_Status) from ola where Booking_Status='Canceled by Customer' --4. List the top 5 customers who booked the highest number of rides:select top 5 Customer_ID, count(Booking_Status)as total_rides from ola group by Customer_IDorder by total_rides desc--5. Get the number of rides cancelled by drivers due to personal and car-related issues:select count(Canceled_Rides_by_Driver) as Driver_cancel_rides from olawhere Canceled_Rides_by_Driver='Personal & Car Related issue' --6. Find the maximum and minimum driver ratings for Prime Sedan bookings:select max(Driver_Ratings) as max_rating, min(Driver_Ratings) as min_rating from olawhere Vehicle_Type='Prime Sedan'--7. Retrieve all rides where payment was made using UPI:select * from ola where Payment_Method='UPI'--8. Find the average customer rating per vehicle type:select Vehicle_Type,avg(Customer_Rating)as Customer_Ratings from ola group by Vehicle_Type--9. Calculate the total booking value of rides completed successfully:select sum(Booking_Value)as Total_Successfully_value from ola where Booking_Status='Success' --10. List all incomplete rides along with the reason:select  Booking_ID,Incomplete_Rides_Reason from ola where Incomplete_Rides='1'------------------------------------------------------------------------------------------------------1. Retrieve all successful bookings:Create view  Total_Successfully_Booking asselect * from ola where Booking_Status= 'Success'--2. Find the average ride distance for each vehicle type:
Create view Avg_ride_distance_vehicle as
select Vehicle_Type, avg(Ride_Distance) as avg_rides from ola group by Vehicle_Type
--3. Get the total number of cancelled rides by customers:Create view Total_cancel_ride_by_customer asselect count(Booking_Status) as Cancel_ride from ola where Booking_Status='Canceled by Customer' --4. List the top 5 customers who booked the highest number of rides:Create view Top_5_customer asselect top 5 Customer_ID, count(Booking_Status)as total_rides from ola group by Customer_IDorder by total_rides desc--5. Get the number of rides cancelled by drivers due to personal and car-related issues:Create view Rides_cancelled_by_Drivers_P_C_Issues asselect count(Canceled_Rides_by_Driver) as Driver_cancel_rides from olawhere Canceled_Rides_by_Driver='Personal & Car Related issue' --6. Find the maximum and minimum driver ratings for Prime Sedan bookings:Create view max_and_min_rating_prime_sedan asselect max(Driver_Ratings) as max_rating, min(Driver_Ratings) as min_rating from olawhere Vehicle_Type='Prime Sedan'--7. Retrieve all rides where payment was made using UPI:Create view UPI_payment asselect * from ola where Payment_Method='UPI'--8. Find the average customer rating per vehicle type:Create view Avg_customer_rating asselect Vehicle_Type,avg(Customer_Rating)as Customer_Ratings from ola group by Vehicle_Type--9. Calculate the total booking value of rides completed successfully:Create view Total_successful_ride_value asselect sum(Booking_Value)as Total_Successfully_value from ola where Booking_Status='Success' --10. List all incomplete rides along with the reason:Create view Incomplete_Rides_Reason asselect  Booking_ID,Incomplete_Rides_Reason from ola where Incomplete_Rides='1'-------------------------------------------------------------------------------------------------------1. Retrieve all successful bookings:select* from Total_Successfully_Booking  --2. Find the average ride distance for each vehicle type:select* from Avg_ride_distance_vehicle--3. Get the total number of cancelled rides by customers:select* from Total_cancel_ride_by_customer--4. List the top 5 customers who booked the highest number of rides:select* from Top_5_customer--5. Get the number of rides cancelled by drivers due to personal and car-related issues:select* from Rides_cancelled_by_Drivers_P_C_Issues--6. Find the maximum and minimum driver ratings for Prime Sedan bookings:select* from max_and_min_rating_prime_sedan--7. Retrieve all rides where payment was made using UPI:select* from UPI_payment--8. Find the average customer rating per vehicle type:select* from Avg_customer_rating--9. Calculate the total booking value of rides completed successfully:select* from Total_successful_ride_value--10. List all incomplete rides along with the reason:select* from Incomplete_Rides_Reason